services:
  saltserver:
    build: .
    tty: true
    ports:
      - 8000
      - 4505
      - 4506
  attaquant:
    image: praqma/network-multitool:alpine-extra
    container_name: attaquant
    ports:
      - 3000
